# Generated by Django 5.2.7 on 2025-12-21 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('achievement_type', models.CharField(choices=[('streak', 'Streak'), ('completion', 'Completion'), ('speed', 'Speed'), ('accuracy', 'Accuracy'), ('social', 'Social'), ('special', 'Special')], max_length=30)),
                ('requirement_type', models.CharField(max_length=30)),
                ('requirement_value', models.IntegerField()),
                ('xp_reward', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('speaking_practices', models.IntegerField(default=0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('streak_maintained', models.BooleanField(default=False)),
                ('daily_goal_achieved', models.BooleanField(default=False)),
                ('weekly_goal_achieved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.achievement')),
            ],
            options={
                'db_table': 'user_achievements',
            },
        ),
    ]
