# Generated by Django 5.2.7 on 2025-12-21 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 21, 21, 9, 44, 980057, tzinfo=datetime.timezone.utc)),
        ),
    ]
