# Generated by Django 5.2.7 on 2025-12-21 21:09

import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('total_lessons', models.IntegerField(default=0)),
                ('total_exercises', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('speaking', 'Speaking Practice'), ('listening', 'Listening Comprehension'), ('writing', 'Writing'), ('translation', 'Translation')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('question_text', models.TextField(blank=True)),
                ('question_audio_url', models.URLField(blank=True, null=True)),
                ('question_image_url', models.URLField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('acceptable_answers', models.JSONField(blank=True, default=list)),
                ('points', models.IntegerField(default=10)),
                ('time_limit_seconds', models.IntegerField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=3)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('order_index', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(max_length=50)),
                ('flag_emoji', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('audio', 'Audio'), ('interactive', 'Interactive')], default='text', max_length=20)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('content_text', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=15)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('order_index', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('key_vocabulary', models.JSONField(blank=True, default=list)),
                ('grammar_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.IntegerField()),
                ('estimated_minutes', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['order_index'],
            },
        ),
    ]
